alert("helloworld")
alert("Error!please enter a valid passward")
alert("Wellcome to Js land Happy coding")
alert("Wellcome to Js land")
alert("Happy coding")
alert("Hello...Ican run Js through my web browser's console")
